apiVersion: v1
kind: ServiceAccount
metadata:
  name: second-scheduler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: second-scheduler-as-admin
subjects:
- kind: ServiceAccount
  name: second-scheduler
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: second-scheduler-config
  namespace: kube-system
data:
  second-scheduler-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1
    kind: KubeSchedulerConfiguration
    profiles:
    - schedulerName: spread-scheduler
      pluginConfig:
      - name: NodeResourcesFit
        args:
          scoringStrategy:
            resources:
            - name: cpu
              weight: 1
            - name: memory
              weight: 1
            requestedToCapacityRatio:
              shape:
              - utilization: 0
                score: 10
              - utilization: 100
                score: 0
            type: RequestedToCapacityRatio
    - schedulerName: pack-scheduler
      pluginConfig:
      - name: NodeResourcesFit
        args:
          scoringStrategy:
            resources:
            - name: cpu
              weight: 1
            - name: memory
              weight: 1
            requestedToCapacityRatio:
              shape:
              - utilization: 0
                score: 0
              - utilization: 100
                score: 10
            type: RequestedToCapacityRatio
    leaderElection:
      leaderElect: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: scheduler
    tier: control-plane
  name: second-scheduler
  namespace: kube-system
spec:
  selector:
    matchLabels:
      component: scheduler
      tier: control-plane
  replicas: 1
  template:
    metadata:
      labels:
        component: scheduler
        tier: control-plane
    spec:
      nodeName: kind-control-plane
      serviceAccountName: second-scheduler
      containers:
      - command:
        - /usr/local/bin/kube-scheduler
        - --config=/etc/kubernetes/second-scheduler/second-scheduler-config.yaml
        - --v
        - "5"
        image: registry.k8s.io/kube-scheduler:v1.25.2
        name: second-scheduler
        resources:
          requests:
            cpu: 0.1
        volumeMounts:
          - name: config-volume
            mountPath: /etc/kubernetes/second-scheduler
      volumes:
        - name: config-volume
          configMap:
            name: second-scheduler-config
