apiVersion: v1
kind: Pod
metadata:
  name: large-cpu-pod
spec:
  schedulerName: default-kube-scheduler
  containers:
    - name: web
      image: nginx
      resources:
        requests:
          cpu: 1.2
  restartPolicy: Never
  
