apiVersion: v1
kind: Pod
metadata:
  name: pod
spec:
  schedulerName: default-kube-scheduler
  containers:
    - name: web
      image: nginx
      resources:
        requests:
          cpu: 0.5
  restartPolicy: Never
