apiVersion: v1
kind: Pod
metadata:
  name: pod-1
spec:
  schedulerName: default-kube-scheduler
  containers:
    - name: web
      image: nginx
  restartPolicy: Never
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-2
spec:
  schedulerName: best-fit-scheduler
  containers:
    - name: web
      image: nginx
  restartPolicy: Never
