apiVersion: kubescheduler.config.k8s.io/v1
kind: KubeSchedulerConfiguration
profiles:
- name: default-scheduler
  plugins:
    queueSort:
      enabled:
      - name: MyAwesomeSort
      disabled:
      - name: "*"
    score:
      disabled:
      - name: PodTopologySpread
      enabled:
      - name: MyCustomPluginA
        weight: 2
      - name: MyCustomPluginB
        weight: 1
  pluginConfig:
  - name: MyCustomPluginA
    args:
      percentageNodeReserved: 50
      learningStrategy: SimpleRegression
